//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMK_practika.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claims_Report
    {
        public int report_id { get; set; }
        public int employee_id { get; set; }
        public int payment_id { get; set; }
    
        public virtual Company_Employee Company_Employee { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
