//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMK_practika.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company_Employee()
        {
            this.Claims_Report = new HashSet<Claims_Report>();
        }
    
        public int employee_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronimyc { get; set; }
        public int role_id { get; set; }
        public Nullable<decimal> phone { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claims_Report> Claims_Report { get; set; }
        public virtual Role Role { get; set; }
    }
}
