//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMK_practika.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance_Claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insurance_Claim()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int claim_id { get; set; }
        public Nullable<System.DateTime> claim_date { get; set; }
        public string description { get; set; }
        public int contract_id { get; set; }
    
        public virtual Insurance_Contract Insurance_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
