//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMK_practika.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Claims_Report> Claims_Report { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Company_Employee> Company_Employee { get; set; }
        public virtual DbSet<Insurance_Claim> Insurance_Claim { get; set; }
        public virtual DbSet<Insurance_Contract> Insurance_Contract { get; set; }
        public virtual DbSet<Medical_Institution> Medical_Institution { get; set; }
        public virtual DbSet<Medical_Service> Medical_Service { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Payment_Status> Payment_Status { get; set; }
        public virtual DbSet<Role> Role { get; set; }
    }
}
