//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMK_practika.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Claims_Report = new HashSet<Claims_Report>();
        }
    
        public int payment_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public int status_id { get; set; }
        public int institution_id { get; set; }
        public int claim_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claims_Report> Claims_Report { get; set; }
        public virtual Insurance_Claim Insurance_Claim { get; set; }
        public virtual Medical_Institution Medical_Institution { get; set; }
        public virtual Payment_Status Payment_Status { get; set; }
    }
}
